apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-d
  template:
    metadata:
      labels:
        app: django-d
    spec:
      containers:
      - name: django
        image: {{ .Values.image.name }}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 1.5Gi
            cpu: "250m"
          limits:
            memory: 1.5Gi
            cpu: "500m"    
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels:
    app: django-d
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: django-d