{{- if false -}}
apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  namespace: default
  labels:
    app: django-pod-app
spec:
  containers:
  - name: django
    image: {{ .Values.image.name }}
    resources:
      requests:
        memory: 1.5Gi
        cpu: "250m"
      limits:
        memory: 1.5Gi
        cpu: "500m"    
    ports:
    - containerPort: 8000
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: django-pod-svc
  labels:
    app: django-pod-app
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: django-pod-app
{{- end -}}