apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: api
version: 0.0.3
dependencies:
  - name: kafka
    version: 20.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
